version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
     - $MONGODB_LOCAL_PORT:27017
    volumes:
      - mongo_data:/data/db

  # Node api service
  api:
    build: .
    ports:
      # local->container
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      PORT: $NODE_DOCKER_PORT
      DB_HOST: mongodb
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      MONGODB_URI: mongodb://mongo_db:27017
    depends_on: 
      - mongo_db

volumes:
  mongo_data: {}